---
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
Name: cloudinary
After: 'framework/*','cms/*'
---
SiteConfig:
  extensions:
    - CloudinaryConfigs